-- ============================================================
-- PATCH_pos_productos_licencia_id_uq_v1.sql
-- Corrige colisión de "id" entre tenants distintos en
-- pos_productos y pos_categorias.
--
-- INCIDENTE REAL (2026-08-17/18): el cliente lodefer@admin.com
-- (PIZZERIA LO DE FERNANDEZ) perdió su carta completa (25+
-- productos, usados en 370 ventas reales) porque otro cliente
-- (cristiansanabria25081999@gmail.com) cargó su propia carta el
-- 13/08/2026 usando los MISMOS ids (2, 3, 4, 5, 6, 8...42) que
-- ya usaba lodefer desde antes. Como "id" era la única PK/UNIQUE
-- de la tabla (global, sin distinguir tenant) y el guardado hace
-- upsert con on_conflict=id, cada producto nuevo de cristiansanabria
-- PISÓ en silencio la fila de lodefer que ya tenía ese id —
-- sin error, sin deleted_at, cambiando hasta el licencia_email
-- de la fila.
--
-- CAUSA: "id" lo genera cada dispositivo como contador LOCAL por
-- tenant (nextProdId = max(ids de ESE cliente)+1, ver
-- js/productos.js) — nunca fue pensado para ser único a nivel
-- global, pero la tabla lo obligaba a serlo. La unicidad real de
-- negocio es (licencia_email, id), no id solo.
--
-- FIX: se agrega una PK interna nueva (row_id) y se mueve la
-- restricción de unicidad de "id" a (licencia_email, id). Esto es
-- seguro sin limpieza previa: como "id" YA era único global, por
-- definición no puede haber pares (licencia_email,id) duplicados
-- hoy — el UNIQUE nuevo no puede fallar por datos existentes.
--
-- Cambios de código que acompañan este patch (ya aplicados en el
-- repo): todos los supaPost(...) de pos_productos/pos_categorias
-- que hacían upsert con on_conflict='id' pasan a
-- on_conflict='licencia_email,id'. Los PATCH por id ahora también
-- filtran por licencia_email donde no lo hacían
-- (admin-inventario.js, actualización de costo tras compra).
--
-- Ejecutar en Supabase SQL Editor. Requiere permisos de owner de
-- la tabla (no alcanza con la anon key).
-- ============================================================

BEGIN;

-- ── PASO 0 (diagnóstico, solo lectura) ──────────────────────
-- Corré esto ANTES de aplicar el patch y confirmá que no hay FKs
-- externas apuntando a la PK actual de pos_productos/pos_categorias
-- (no debería haber ninguna — pos_ventas guarda los items como JSON,
-- no como FK — pero mejor confirmar antes de tocar la PK en prod):
--
-- SELECT conname, conrelid::regclass AS tabla_que_referencia
-- FROM pg_constraint
-- WHERE confrelid IN ('public.pos_productos'::regclass, 'public.pos_categorias'::regclass)
--   AND contype = 'f';
--
-- Si esa consulta devuelve filas, AVISAR antes de seguir — este
-- patch no está pensado para tocar FKs.

-- ── PASO 1: pos_productos ────────────────────────────────────
ALTER TABLE public.pos_productos
  ADD COLUMN IF NOT EXISTS row_id bigint GENERATED BY DEFAULT AS IDENTITY;

DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'public.pos_productos'::regclass AND contype = 'p'
  LOOP
    EXECUTE format('ALTER TABLE public.pos_productos DROP CONSTRAINT %I', r.conname);
  END LOOP;
END $$;

ALTER TABLE public.pos_productos ADD PRIMARY KEY (row_id);
ALTER TABLE public.pos_productos
  ADD CONSTRAINT pos_productos_licencia_id_uq UNIQUE (licencia_email, id);

-- ── PASO 2: pos_categorias (mismo problema, mismo fix) ──────
ALTER TABLE public.pos_categorias
  ADD COLUMN IF NOT EXISTS row_id bigint GENERATED BY DEFAULT AS IDENTITY;

DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'public.pos_categorias'::regclass AND contype = 'p'
  LOOP
    EXECUTE format('ALTER TABLE public.pos_categorias DROP CONSTRAINT %I', r.conname);
  END LOOP;
END $$;

ALTER TABLE public.pos_categorias ADD PRIMARY KEY (row_id);
ALTER TABLE public.pos_categorias
  ADD CONSTRAINT pos_categorias_licencia_id_uq UNIQUE (licencia_email, id);

COMMIT;

-- ── PASO 3 (verificación, solo lectura, correr después) ─────
-- Confirmar que las nuevas restricciones quedaron bien:
--
-- SELECT conname, contype, pg_get_constraintdef(oid)
-- FROM pg_constraint
-- WHERE conrelid IN ('public.pos_productos'::regclass, 'public.pos_categorias'::regclass)
--   AND contype IN ('p','u');
--
-- A partir de acá, PostgREST acepta on_conflict=licencia_email,id
-- (que es lo que ya usa el código del frontend). Un id repetido
-- entre dos tenants distintos ya NO puede pisar la fila del otro —
-- como mucho, produce un conflicto dentro del MISMO tenant, que es
-- el comportamiento correcto (upsert = editar el propio producto).
